site_name: PandoraSat
nav:
    - Home: README.md
    - API:
      - PandoraSat: pandorasat.md
      - NIRDA: irdetector.md
      - VISDA: visibledetector.md
      - Hardware: hardware.md
      - Orbit: orbit.md
    - Notebooks:
      - PandoraSat Demo: intro-to-pandorasat.ipynb
theme:
  name: "material"
  icon:
      logo: material/clipboard
repo_url: https://github.com/pandoramission/pandora-sat
plugins:
  - search
  - mkdocs-jupyter:
      execute: False
      include_source: True
      ignore_h1_titles: False
  - mkdocstrings:
      watch:
        - src/pandorasat
