site_name: pandorasat
site_url: https://pandoramission.github.io/pandora-sat/
docs_dir: docs

nav:
  - Home: README.md
  - Example Usage: intro-to-pandorasat.ipynb
  - NIR Detector: irdetector.md
  - Visible Detector: visibledetector.md
  - Hardware: hardware.md
  - Orbit: orbit.md
  
theme:
  name: "material"
  icon:
    logo: material/clipboard
  features:
    - content.code.copy
    - content.code.annotate 
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/pandoramission/pandora-sat
plugins:
  - search
  - include-markdown
  - mkdocs-jupyter:
      execute: false
  - mkdocstrings:
      watch:
        - src/packagename
      default_handler: python      
      handlers:
        python:
          options:
            show_source: false
            inherited_members: true
            filters:
              - "!^_"
            heading_level: 2  # Ensures API docs have an H2 header for structure
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - tables
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/force_mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js